### ISSUE TITLE
OSX 10.10.5 Crash

### ISSUE THREAD

**Issue by 4lejandrito** [Scalingo/heroku2scalingo#8]
Hi, I just downloaded the [latest release for Mac](https://github.com/Scalingo/heroku2scalingo/releases/download/v0.1.3/heroku2scalingo_0.1.3_darwin_amd64.zip) and when I run `./heroku2scalingo <name of my app>` I get the following error:
```
A Heroku authentication token has been found, do you allow us to use it? [y/n] y
-----> Heroku authentication... OK
-----> Scalingo authentication... OK
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x3665]

goroutine 1 [running]:
main.main()
	/Users/gabrielmetzger/Documents/Workspace/Go/src/github.com/Scalingo/heroku2scalingo/main.go:95 +0xbb5

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [chan receive]:
github.com/Scalingo/heroku2scalingo/signals.Handle()
	/Users/gabrielmetzger/Documents/Workspace/Go/src/github.com/Scalingo/heroku2scalingo/signals/handler.go:18 +0x25f
created by main.main
	/Users/gabrielmetzger/Documents/Workspace/Go/src/github.com/Scalingo/heroku2scalingo/main.go:76 +0x1da

goroutine 11 [runnable]:
net/http.(*persistConn).readLoop(0xc2080920b0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc2080920b0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcb
```

Also note the `/Users/gabrielmetzger/Documents/Workspace/Go/src/github` lines in the stacktrace... Maybe you don't want them to point to gabrielmetzger as the culprit! :)

Hope this helps!

**Comment by Soulou** [comment]
Thanks for reporting the issue, that's obviously a problem in the command line tool. We are now patching the this.

As a workaround (waiting for our release), you can do the following:

- Download our CLI at [http://cli.scalingo.com](http://cli.scalingo.com)
- Run `scalingo login`
- Retry `heroku2scalingo`, it should work without crashing like this.

Apologies for the issue, we're on it

**Comment by 4lejandrito** [comment]
That makes sense because I didn't login to scalingo at all from my terminal and I was confused when the tool displayed `-----> Scalingo authentication... OK`

Thanks!

**Comment by Soulou** [comment]
https://github.com/Scalingo/heroku2scalingo/releases/tag/v0.1.4

New release, bug fixed :-)

**Comment by Soulou** [comment]
Thank you for reporting ;-)
